// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using RaceMng.Database.Classes;

namespace RaceMng.Database.Models.Bos;

[PrimaryKey("CategoryId", "CompetitorId")]
[Table(nameof(CompetitorCategory), Schema = Constants.SchemaRc)]
public partial class CompetitorCategory
{
    [Key]
    [Column("Category_Id")]
    public int CategoryId { get; set; }

    [Key]
    [Column("Competitor_Id")]
    public int CompetitorId { get; set; }
 /// <summary>
 /// public FormMode FormMode { get; set; }
 /// </summary>

  public int? Number { get; set; }

    public TimeOnly? Time { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Created { get; set; }

  public virtual Competitor Competitor { get; set; }
  public virtual Category Category { get; set; }
}