// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using RaceMng.Database.Classes;

namespace RaceMng.Database.Models.Bos;

[Table(nameof(Competitor), Schema = Constants.SchemaRc)]
public partial class Competitor
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string FirstName { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string LastName { get; set; }

    public int BirthYear { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Team { get; set; }

    [Column("Sex_Id")]
    public int SexId { get; set; }

    [ForeignKey("SexId")]
    [InverseProperty("Competitors")]
    public virtual Sex Sex { get; set; }
}