// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using RaceMng.Database.Classes;

namespace RaceMng.Database.Models.Bos;

[Table(nameof(Race), Schema = Constants.SchemaRc)]
public partial class Race
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string Name { get; set; }

    //[Column(TypeName = "date")]
    public DateOnly Date { get; set; }

    public bool IsValid { get; set; }

    [InverseProperty("Race")]
    public virtual ICollection<Category> Categories { get; } = new List<Category>();
}