// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using RaceMng.Database.Classes;

namespace RaceMng.Database.Models.Bos;

[Table(nameof(Sex), Schema = Constants.SchemaRc)]
public partial class Sex
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(10)]
    [Unicode(false)]
    public string Name { get; set; }

    [InverseProperty("Sex")]
    public virtual ICollection<Category> Categories { get; } = new List<Category>();

    [InverseProperty("Sex")]
    public virtual ICollection<Competitor> Competitors { get; } = new List<Competitor>();
}