// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Apollo.SmartFleet.Database.Data;
using Microsoft.EntityFrameworkCore;
using RaceMng.Database.Models.Bos;

namespace RaceMng.Database.Context;

public partial class RaceMngContext : DbContext
{
  public RaceMngContext(DbContextOptions<RaceMngContext> options)
      : base(options)
  {
  }

  public virtual DbSet<Category> Categories { get; set; }

  public virtual DbSet<Competitor> Competitors { get; set; }

  public virtual DbSet<CompetitorCategory> CompetitorCategories { get; set; }

  public virtual DbSet<Race> Races { get; set; }

  public virtual DbSet<Sex> Sexes { get; set; }

  protected override void OnModelCreating(ModelBuilder modelBuilder)
  {
    modelBuilder.UseCollation("Czech_CI_AS");

    modelBuilder.Entity<Category>(entity =>
    {
      entity.HasOne(d => d.Race).WithMany(p => p.Categories)
              .OnDelete(DeleteBehavior.ClientSetNull)
              .HasConstraintName("FK_RaceCategory");

      entity.HasOne(d => d.Sex).WithMany(p => p.Categories)
              .OnDelete(DeleteBehavior.ClientSetNull)
              .HasConstraintName("FK_SexCategory");
    });

    modelBuilder.Entity<Competitor>(entity =>
    {
      entity.HasOne(d => d.Sex).WithMany(p => p.Competitors)
              .OnDelete(DeleteBehavior.ClientSetNull)
              .HasConstraintName("FK_SexCompetitor");
    });

    modelBuilder.Entity<CompetitorCategory>(entity =>
    {
      entity.Property(e => e.Created).HasDefaultValueSql("(getdate())");
    });

    OnModelCreatingPartial(modelBuilder);

    modelBuilder.Seed();
  }

  partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}